# Generated by Django 2.0.7 on 2018-08-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('uid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=500)),
                ('channel', models.CharField(max_length=50)),
                ('send_to', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=25, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
